author: "Kamrujjaman Khan <>"
category: "http"
summary: "HTTP interface to POST stanzas into ejabberd"
home: "https://github.com/processone/ejabberd-contrib/tree/master/"
url: "git@github.com:processone/ejabberd-contrib.git"
